### ISSUE TITLE
Broken link on dcraw-c-code-annotated.html

### ISSUE THREAD

**Issue by RalphCorderoy** [ellelstone/elles_icc_profiles#3]
Sorry, this isn't the right way to contact you, but I can't find an email address and it is related.
Your useful https://ninedegreesbelow.com/photography/dcraw-c-code-annotated.html has a broken link.
_dcraw c code "adobe_coeff" table_ refers to localhost as a path.
Google thinks the correct page is https://ninedegreesbelow.com/photography/dcraw-c-code-annotated.html.

**Comment by ellelstone** [comment]
Hi Ralph,

Yesterday I sent you an email, probably to the wrong return address. So I'll just answer here:
I couldn't find a broken link (doesn't mean there isn't one, of course).

On my website this page:

https://ninedegreesbelow.com/photography/dcraw-c-code-annotated.html

doesn't have any information on the adobe_coeff table. But it does have a link (in the section on google insanity) to this page:

https://ninedegreesbelow.com/files/dcraw-c-code-annotated-code.html

which does have an "in page" link to the section on the adobe_coeff table:

https://ninedegreesbelow.com/files/dcraw-c-code-annotated-code.html#K1

Is it possible that you might be looking at a cached page or something? I did check the actual source code on the two pages I just mentioned - no "localhost" on either page.

**Comment by RalphCorderoy** [comment]
Hi Elle, Firstly, I've updated my GitHub profile to show my email address.

I've misled you, sorry for wasting your time. I've re-checked and it's https://ninedegreesbelow.com/photography/camera-profile-make-target-shot.html with the problem. I was telling someone else about your site and must have mixed up what I was pasting.

```
$ wget -nv https://ninedegreesbelow.com/photography/camera-profile-make-target-shot.html
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
2021-02-04 17:29:24 URL:https://ninedegreesbelow.com/photography/camera-profile-make-target-shot.html [28826] -> "camera-profile-make-target-shot.html" [1]
$ tr -s '<>' \\012 <camera-profile-make-target-shot.html | grep localhost
a href="http://localhost/photography/dcraw-c-code-annotated.html"
$
```

**Comment by ellelstone** [comment]
Hi Ralph,

Thanks very much! for letting me know about the broken link. I just uploaded the page with the corrected link. You might need to clear your cache to get the new page.

Best,
Elle
